name: Prettier

on:
  push:
    branches:
      - main
      - feature/*
      - fix/*

jobs:
  prettier:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: yarn install

      - name: Run prettier
        run: yarn fmt --write .

      - name: Auto Commit
        if: success()
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Apply Code Formatter Change
          commit_all: true
